project:
  type: website
  output-dir: docs

website:
  title: "Douglas B. Sponsler"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- about.qmd
      - research.qmd
      - teaching.qmd
      - pubs.qmd
      - skills.qmd
      - media.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true

about:
  template: trestles
  
# research:
#   template: marquee
#   
# teaching:
#   template: marquee
# 
# pubs:
#   template: marquee
  
